### ISSUE TITLE
Xcode iOS Simulators not working.

### ISSUE THREAD

**Issue by abaza7** [1nferious/Dell-XPS-15-7590-MacOS-Monterey--12.0.1--Hackintosh#1]
Hi, first of all thanks for the good work. I have the same device as you with the except of 16GB RAM instead of 32GB. Everything works perfectly except the xcode iOS simulators, they only show a black screen and I have read online that this is an HW acceleration issue but I am not sure, do you have the same issue?

thanks in advance.

**Comment by 1nferious** [comment]
Hey abaza, thank you for your feedback. I'm sorry to hear you are experiencing an issue with my current build; My experience with XCode has been fine running any iOS simulators, I do have a pending update for XCode maybe it depends on the specific build? I'm currently on vacation and the wifi here is a slow thus I'll have to wait until I get home to update to the latest version of XCode.
